# Generated by Django 3.0.7 on 2020-06-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('favorite', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('avt', models.ImageField(upload_to='')),
                ('urlFace', models.URLField()),
            ],
        ),
    ]
