# Generated by Django 3.0.7 on 2020-06-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avt',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
