# Generated by Django 3.0.7 on 2020-06-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelProfile', '0002_auto_20200607_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avt',
            field=models.ImageField(default='../media/avtDefault.jpg', upload_to=''),
        ),
    ]
